# -- CONSTANTS -- #
CHESS_BOARD_SIZE = 500
REPERTOIRE_ROOT = 'chess_repertoire'

# -- View constants -- #
MAX_OPENING_PER_PAGE = 4
MAX_VARIATION_PER_PAGE = 4

# -- Lengths -- #
MAX_LENGTH = 50
OPENING_MAX_LENGTH = 400
VARIATION_MAX_LENGTH = 200
FILE_MAX_LENGTH = 500
MOVE_MAX_LENGTH = 6